/**
 * Per-page <lastmod> dates for the sitemap.
 *
 * The failure this avoids: stamping `new Date()` on every URL at build time.
 * That tells Google all 64 pages changed on every deploy, including ones
 * nobody touched. Google treats lastmod as a hint and discounts sources whose
 * pages are perpetually "just modified", so it throws away a real signal.
 *
 * Dates live in lastmod.json, committed to the repository and regenerated by
 * `npm run lastmod`. A page keeps its date until its content fingerprint
 * changes, so the sitemap reports real edits rather than build times.
 */

import { TOOLS } from '@/tools/registry';
import { HOME_KEY, contentFingerprint, homeFingerprint } from './fingerprint';
import manifest from './lastmod.json';

export { HOME_KEY, contentFingerprint, homeFingerprint };

export interface LastmodEntry {
  /** ISO date, e.g. "2026-09-23". Whole days: sitemaps need no finer. */
  lastmod: string;
  /** Fingerprint of the content that produced this date. */
  fingerprint: string;
}

const MANIFEST = manifest as Record<string, LastmodEntry>;

/**
 * The recorded date for a page, or undefined if it has none.
 *
 * Returning undefined rather than today's date is the point: a page with no
 * recorded date omits lastmod entirely instead of inventing one.
 */
export function lastmodFor(slug: string): string | undefined {
  return MANIFEST[slug]?.lastmod;
}

/**
 * Pages whose content no longer matches the manifest.
 *
 * A test calls this, so editing copy without regenerating fails the build
 * rather than quietly shipping a sitemap that understates the change.
 */
export function staleEntries(): string[] {
  const stale: string[] = [];

  for (const tool of TOOLS) {
    const entry = MANIFEST[tool.slug];
    if (!entry || entry.fingerprint !== contentFingerprint(tool)) {
      stale.push(tool.slug);
    }
  }

  const home = MANIFEST[HOME_KEY];
  if (!home || home.fingerprint !== homeFingerprint(TOOLS)) {
    stale.push(HOME_KEY);
  }

  return stale;
}
